name: chall2026-military-drones

services:
  military-drones:
    image: athack-ctf/chall2026-military-drones:latest
    container_name: chall2026-military-drones
    build:
      context: .
      dockerfile: source/Dockerfile
    ports:
      - "53014:5000"